export interface Usuario{
    id?: number,
    name: string,
    lastName: string,
    user: string,
    password: string,
    email: string,
    legajo: string,
    fechaNac: string,
    color: string,
    habilitado: boolean,
    diasFavor: number,
    diasVacaciones: number,
    horasFavor: number,
}